In [1]:
import numpy as np


## Создание массива


In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

## Изменение форма масива .shape

In [3]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Создание нового массива не меня форму старого .reshape()


In [7]:
arr_new = arr.reshape((2, 4), order= 'F') #order= 'F' изменение формы по столбцам
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

## Замена строк и столбцов местами .transpose()


In [11]:
arr = np.arange(8)
arr.shape = (2 , 4)
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

## Создание последовательности чисел от и до .linspase()

In [14]:
arr = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
arr

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

## Индексация по индексам в многомерном массиве

In [15]:
arr[1, 2]

3.0

In [16]:
arr[:2, 2]

array([1., 3.])

In [ ]:
arr[1:, 2:4]

In [18]:
arr[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [19]:
arr[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

## Сортировка массива 

In [20]:
arr = np.array([23, 12, 45, 12, 23, 4, 15, 3])
arr_new = np.sort(arr) # запись в новукю переменную 
arr.sort() # замена существующей


##  Извлечение из эллементов масива квадратных корней

In [22]:
data = np.array([4 ,9, -4, 3])
roots = np.sqrt(data)
print(roots)

[2.         3.         1.41421356 1.73205081]


## nan в массиве

In [ ]:
np.isnan(roots) # поиск nan в массиве
roots[np.isnan(roots)] = 0 # замена nan в масиве на число